//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminImage
    {
        public AdminImage()
        {
            this.UserPostCardImages = new HashSet<UserPostCardImage>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<bool> ByAdmin { get; set; }
    
        public virtual ImageCategory ImageCategory { get; set; }
        public virtual ICollection<UserPostCardImage> UserPostCardImages { get; set; }
    }
}
