//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string Message { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsResolved { get; set; }
        public Nullable<System.DateTime> ResolvedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> RequestType { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsSubscriber { get; set; }
        public Nullable<bool> IsFromWeb { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSeenByAdmin { get; set; }
    }
}
