//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HyggeMailEntities : DbContext
    {
        public HyggeMailEntities()
            : base("name=HyggeMailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminImage> AdminImages { get; set; }
        public virtual DbSet<BlogDetail> BlogDetails { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<CMSPage> CMSPages { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<ImageCategory> ImageCategories { get; set; }
        public virtual DbSet<MembershipPlan> MembershipPlans { get; set; }
        public virtual DbSet<NotificationStack> NotificationStacks { get; set; }
        public virtual DbSet<PushNotification> PushNotifications { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<tblTestimonial> tblTestimonials { get; set; }
        public virtual DbSet<UserAddressBook> UserAddressBooks { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserHistory> UserHistories { get; set; }
        public virtual DbSet<UserOrder> UserOrders { get; set; }
        public virtual DbSet<UserPostCard> UserPostCards { get; set; }
        public virtual DbSet<UserPostCardImage> UserPostCardImages { get; set; }
        public virtual DbSet<UserPostCardRecipient> UserPostCardRecipients { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTransaction> UserTransactions { get; set; }
    }
}
