//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotification
    {
        public int PushNotificationId { get; set; }
        public string DeviceId { get; set; }
        public string Message { get; set; }
        public short DeviceTypeId { get; set; }
        public Nullable<short> TypeId { get; set; }
        public short StatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ErrorMessage { get; set; }
    }
}
