//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionId { get; set; }
        public System.Guid Token { get; set; }
        public int UserId { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public Nullable<short> DeviceType { get; set; }
    
        public virtual User User { get; set; }
    }
}
