//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.NotificationStacks = new HashSet<NotificationStack>();
            this.Sessions = new HashSet<Session>();
            this.UserAddressBooks = new HashSet<UserAddressBook>();
            this.UserHistories = new HashSet<UserHistory>();
            this.UserPostCards = new HashSet<UserPostCard>();
            this.UserPostCardImages = new HashSet<UserPostCardImage>();
            this.UserTransactions = new HashSet<UserTransaction>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> MemberShipType { get; set; }
        public string ForgotUID { get; set; }
        public string ActivatedUID { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastLogout { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public Nullable<short> AuthenticationType { get; set; }
        public Nullable<short> DeviceType { get; set; }
        public string DeviceToken { get; set; }
        public string Facebook_ID { get; set; }
        public Nullable<bool> OrderPlacedNotification { get; set; }
        public Nullable<bool> OrderStatusNotification { get; set; }
        public Nullable<int> CardsCount { get; set; }
        public Nullable<bool> IsToolTipShow { get; set; }
    
        public virtual MembershipPlan MembershipPlan { get; set; }
        public virtual ICollection<NotificationStack> NotificationStacks { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<UserAddressBook> UserAddressBooks { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual ICollection<UserHistory> UserHistories { get; set; }
        public virtual ICollection<UserPostCard> UserPostCards { get; set; }
        public virtual ICollection<UserPostCardImage> UserPostCardImages { get; set; }
        public virtual ICollection<UserTransaction> UserTransactions { get; set; }
    }
}
