//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserID { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public Nullable<bool> OrderPlacedNotification { get; set; }
        public Nullable<bool> OrderStatusNotification { get; set; }
        public string Phone { get; set; }
        public string FacebookID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ProfileImagePath { get; set; }
        public string ProfileImageName { get; set; }
    
        public virtual User User { get; set; }
    }
}
