//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPostCardRecipient
    {
        public UserPostCardRecipient()
        {
            this.UserHistories = new HashSet<UserHistory>();
        }
    
        public int ID { get; set; }
        public int FKUserAddressBookId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<int> UserPostCardID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<bool> IsError { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public string RejectedReason { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public int CardStatus { get; set; }
    
        public virtual UserAddressBook UserAddressBook { get; set; }
        public virtual ICollection<UserHistory> UserHistories { get; set; }
        public virtual UserPostCard UserPostCard { get; set; }
    }
}
