//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransaction
    {
        public UserTransaction()
        {
            this.UserHistories = new HashSet<UserHistory>();
        }
    
        public int ID { get; set; }
        public string TransactionID { get; set; }
        public string Gateway { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public int PlanID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual MembershipPlan MembershipPlan { get; set; }
        public virtual ICollection<UserHistory> UserHistories { get; set; }
        public virtual User User { get; set; }
    }
}
