//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddressBook
    {
        public UserAddressBook()
        {
            this.UserPostCardRecipients = new HashSet<UserPostCardRecipient>();
        }
    
        public int ID { get; set; }
        public int UserIDFK { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public bool IsPermanent { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string KeywordFamousFor { get; set; }
        public string Agency { get; set; }
        public Nullable<bool> AddressVerified { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> AddedByAdmin { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserPostCardRecipient> UserPostCardRecipients { get; set; }
    }
}
