//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyggeMail.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPostCard
    {
        public UserPostCard()
        {
            this.UserPostCardImages = new HashSet<UserPostCardImage>();
            this.UserPostCardRecipients = new HashSet<UserPostCardRecipient>();
        }
    
        public int ID { get; set; }
        public string CardFront { get; set; }
        public string CardBack { get; set; }
        public Nullable<System.DateTime> ShippedOn { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<bool> IncludeAddress { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string CardFrontJson { get; set; }
        public string CardBackJson { get; set; }
        public string CardFrontPath { get; set; }
        public string CardBackPath { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<bool> IsOrderPlaced { get; set; }
        public Nullable<System.DateTime> OrderPlacedOn { get; set; }
        public string CardBackJsonWithIFrame { get; set; }
        public string CardBackPathWithIFrame { get; set; }
        public string CardBackWithFrame { get; set; }
    
        public virtual UserOrder UserOrder { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserPostCardImage> UserPostCardImages { get; set; }
        public virtual ICollection<UserPostCardRecipient> UserPostCardRecipients { get; set; }
    }
}
